version: '3.8'

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    networks:
      - webnet

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: testdb
      MYSQL_USER: root
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    networks:
      - webnet

  adminer:
    image: adminer:latest
    ports:
      - "8080:8080"
    networks:
      - webnet

  api:
    image: node-js.api
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    networks:
      - webnet

networks:
  webnet:
    driver: bridge
